### ISSUE TITLE
2016-07-07-slacker.img is missing?

### ISSUE THREAD

**Issue by leosco** [mheinzel66/Slacker2000#1]
Trying to go through the setup instructions in `Slacker2000/slackerFirmware/setup notes.txt`

but I'm stuck on 
```
//copy impage to disk
sudo dd bs=1M if=2016-07-07-slacker.img of=/dev/sdb; sync
```

Where's the `.img` file? Can't find it anywhere on the repo or on your site

**Comment by mariusl** [comment]
Has this been resolved? I am also looking for the image file please

**Comment by leosco** [comment]
Doesn't seem like this is maintained. Could have just been something maintainer forgot to commit and it's breaking the setup process.
